
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

rest_command:
  send_numbers:
    url: "http://localhost:8080/?cab={{ states('input_number.cab_level') }}&tail={{ states('input_number.tailgate_level') }}"
    method: GET
  set0:
    url: "http://localhost:8080/?cab=0&tail=0"
    method: GET
  set25:
    url: "http://localhost:8080/?cab=25&tail=25"
    method: GET
  set50:
    url: "http://localhost:8080/?cab=50&tail=50"
    method: GET
  set75:
    url: "http://localhost:8080/?cab=75&tail=75"
    method: GET
  set100:
    url: "http://localhost:8080/?cab=100&tail=100"
    method: GET

rest:
  - resource: "http://localhost:8080/"
    scan_interval: 1
    sensor:
      - name: "tail"
        value_template: "{{ value_json['tail']}}"
      - name: "cab"
        value_template: "{{ value_json['cab']}}"
command_line:
     sensor:
     -name: CPU Temperature
     -command: "cat /sys/class/thermal/thermal_zone0/temp"
     -unit_of_measurement: "°C"
     -value_template: '{{ value | multiply(0.001) | round(1) }}'
